---
collections:
  - name: community.general
    version: ">=6.0.0"
  - name: community.libvirt
    version: ">=1.2.0"
  - name: kubernetes.core
    version: ">=2.4.0"
  - name: community.crypto
    version: ">=2.0.0"
  - name: ansible.posix
    version: ">=1.4.0"

roles:
  - name: geerlingguy.pip
    version: ">=2.2.0"
  - name: geerlingguy.docker
    version: ">=6.0.0"
