---
- name: Create Ubuntu version directory
  file:
    path: "{{ pxe_http_root }}/ubuntu/{{ ubuntu_version.version }}"
    state: directory
    owner: www-data
    group: www-data
    mode: '0755'

- name: Create architecture subdirectories
  file:
    path: "{{ pxe_http_root }}/ubuntu/{{ ubuntu_version.version }}/{{ item }}"
    state: directory
    owner: www-data
    group: www-data
    mode: '0755'
  loop: "{{ ubuntu_version.arch }}"


- name: Download Ubuntu 24.04+ netboot files
  get_url:
    url: >-
      {{ netboot_base_url }}/{{ ubuntu_version.codename }}/{{ netboot_path }}/{{ item[0] }}/{{ item[1] }}
    dest: >-
      {{ pxe_http_root }}/ubuntu/{{ ubuntu_version.version }}/{{ item[0] }}/{{ item[1] }}
    owner: www-data
    group: www-data
    mode: '0644'
    timeout: 300
  vars:
    netboot_base_url: >-
      {{ 'https://releases.ubuntu.com' if item[0] == 'amd64' else 'https://cdimage.ubuntu.com/releases' }}
    netboot_path: >-
      {{ 'netboot' if item[0] == 'amd64' else 'release/netboot' }}
  with_nested:
    - "{{ ubuntu_version.arch }}"
    - ["linux", "initrd"]
  when: ubuntu_version.version is version('24.04', '>=')
