---
- name: Ensure needed packages exist
  hosts: all
  become: true
  tasks:
    - name: Prepare needed packages
      apt:
        name:
          - kea-dhcp4-server
          - net-tools
        state: present
        update_cache: true
