---
- name: Verify
  hosts: pxe
  gather_facts: false
  tasks:
    - name: Execute pytest suite
      delegate_to: localhost
      ansible.builtin.command:
        cmd: >
          pytest -q -ra molecule/pxe/tests
