---
- name: PXE setup
  import_playbook: 01_pxe.yml

- name: Hypervisor setup
  import_playbook: 02_hypervisor.yml

- name: VM provisioning
  import_playbook: 03_vm.yml

- name: K3s cluster
  import_playbook: 04_k3s.yml

- name: Observability stack
  import_playbook: 05_observability.yml

- name: Integration checks
  import_playbook: 06_integration.yml

- name: Homelab Infrastructure Deployment Complete
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Display deployment summary
      debug:
        msg: "Complete homelab infrastructure deployment finished"
