---
galaxy_info:
  author: Danil Aliforenko
  description: Observability configuration for homelab infrastructure
  license: MIT
  min_ansible_version: 2.12
  platforms:
    - name: Ubuntu
      versions:
        - focal
        - jammy
    - name: Debian
      versions:
        - bullseye
        - bookworm

dependencies: []
