---
galaxy_info:
  author: Danil Aliforenko
  description: Pxe configuration for homelab infrastructure
  license: MIT
  min_ansible_version: "2.12"
  platforms:
    - name: Ubuntu
      versions:
        - focal
        - jammy

dependencies: []
